language: java
script: mvn -P server package -DskipTests
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
notification:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "pd40IwghOSb4Ztl2tFgn5Gb1zHDcyW6ltL+aMVf2Ph1+fG0i4C16zSfFcgvGEKNWI4yhYKKSeocmQn9ajlPo4ZEVhvs49vlOsCfNTSsZL6HcteDUrk33Waxbsv4oMWs9ZZ+H3MYLKL9MiK1a8KLxz67Bfb3MnvMPFNA6q4z9FDLR8zwnBz7BZxNivDUoNjV0M6OVBMY3aUsssKboXv4BT4BzQpPDYisa+MCJo4STiKIIn1YyiLuxVvhCOod+9thzOgNqWu1GWMHN4zIm6oEPFLNliwEkA3wszyfskJRMsc4bfdphyUgdUx7HRhR3cuhXv+EP+td0T76Ztdff+h5rayjeIdBRMjjiw9vR1q5cZyoT92nT9mqjnXACQGcaLOjEXTrrULlbNTwTMPSOhbAnpx9K1I2tSBlh84rwZv/THeCzU5EAdyBlMPFBvT69WwP03xCSgyOmYBVTMtgVAQhkkLNS6UW/nDXiAyZKhoMuG3I+atO6py/lbRxQCaI6oijMObBGcK6EtlHdGSPlwOWsm8jOPOqqqKOkAlX684uaqj37nZhk+mylfX/5466Vane55IVZwI8DBnHC+NpGcFn5OzbnVXk5jGcxdNc6isgIlnGS82iLVU1VczQHrneg28MYFbQELxfsXQ+1VQaO0wqIEn8ZNyLXOF1ho3+2DVgdsDs="
