language: java
script: mvn -P server package -DskipTests
jdk: oraclejdk8
cache:
  directories:
    - "$HOME/.m2"

notification:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "tFCpoMNFP3WNMZkRuJ59gpj8vazkucnsO9npLj2gtDw/E5LAZHibiDcYBFaegJ6gGkZIHt9Ue1w5Wq84y8zQQMa667wu8dzOKmNG517om7VGEioGQ3gqFZGCRLxUoVejiIYcVgg1c0vkHi9li4FmIz5BVI1ktY3s/naVGuFY9+8JEuoDhS9UCrjtW4emXeUnOClp39rPukz5dpxe20tqg/wRy+VumlB1OZKLqji9AYgwpUhjBDwA4Q/BlXGA7jxcw8fMxoaBRDHSmoaQesPSQUnQzgy+Aqz6WryvAa1WuSH0NyhZEgfljjiySzXJ3C9HSNRJ0ZWuj4KqecsLSycU71s9XVZHh6A7ef/9MZkJ8tfChQJI8LaEvndz4u0L99os2+9eZjwxM4VzRa68sS3k2706Tf8y6mFAkvkPqK1jct5GK5PfDKAhNOfgmWH0TpcBBjES9XlIGm/sRgvYL7mi7Ju3+DSS8IotF2PKJESi0uGYt508k6+d/6ZDZnQScI9xwvehrqsYLxSN3W1VQtIugNNtWtZkquEa/W8GXHApvXp4WDcqmvQtnFf1b0LfxTHMb7c1WBT6NiT0cG5kM77x8HohSMo7889k+YblgQ6d/Q6IBg1n/hrPh/msCsVW1EGFYqS42Xc3QZLbnRnfDrkzXUrgrn/TkbxApGqVywgI5Rg="
