version: '3'

services:

  wikipedia:
    image: lambdacube/wikipedia-api:latest
    ports:
      - "8088:8080"
    volumes:
      - ./logs:/usr/share/wikipedia/logs
      - ./conf:/usr/share/wikipedia/conf
