FROM openjdk:8u131-jre-alpine

WORKDIR /usr/share/wikipedia

# basic functionality
ENV LANG="en_US.UTF-8" TZ="Europe/Berlin"

EXPOSE 8080

# add folder

ADD wikipedia-rest/target/wikipedia-rest-${project.version}-dist/ .

CMD ["bin/start.sh"]
